---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certificate
  namespace: kube-system
  labels:
    k8s-app: certificate
    kubernetes.io/cluster-service: "true"
data:
  ca.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIQKJla1CR5aq5BETDm0XMFmTANBgkqhkiG9w0BAQsFADA6
    MRkwFwYDVQQLExB6OHpzdzVsdHp2a3Z4c25nMR0wGwYDVQQDExRlbGFzdGljc2Vh
    cmNoLXNhbXBsZTAeFw0xOTA3MjAyMTMzMTRaFw0yMDA3MTkyMTM0MTRaMDoxGTAX
    BgNVBAsTEHo4enN3NWx0enZrdnhzbmcxHTAbBgNVBAMTFGVsYXN0aWNzZWFyY2gt
    c2FtcGxlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyV5C9t/4h2Uc
    66mybEQ98qloEnicbK6JW4gSNcclPb7mThAQSK2X03+EdwBOx0iiMS2EV13E2xFu
    AOJQsHqHl8yzMVcpAbW1XcC6k/i+0OKLEwzG+ogG+0l8bU57MuEm/SZ5KewMvryK
    QiRtlUFPvLIUpiMTop1vzL3J7/Hi82b8viDTKRtkR9SfelUGnBitL738UQsEeDAT
    aAXD/1E/MMEo7UyGYPJNahjfluFQFqwC4amsq0df2aV5S9hft3LfZbgsEpsBz93B
    WeWnA9HZTi4UnaF/m4UxVE8SkWzNsphAvGpkbm3IrhtSl7OcXsI/prDNtLEDWgMa
    Qu4Vtfw9dwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQAD
    ggEBAJmJdQV3memySDcCyzaZdeyHniRF9S9uWOyWj79WNgE+91berlA+hFITY/hi
    NnJ0aAkEXklbftf9enuqaFmitAKF1h5norMZWc2dIAdX9Pbzmk4JuJuv80NRhOMm
    z3Xd9CP9edFHyMI+dsX4dCTmv35LaWoSsjDA7j3y+7Tk1L19WIvm38t2qJTucpO3
    Ep3K+vb2WT49+QL0tTK7g96qa6R0F++Xv2x/mJUcWDFgGJu7tI4aCz7OFfW9ElN7
    Zbe0W+ZD/QYQtgZfMemuWJ8+RBlG3YKRsTn1QahSam7aw5A1ha8QAyOXVrhB9ez6
    hP/jVnver/SRHeMEKTlfyAKa3Ro=
    -----END CERTIFICATE-----
